### ISSUE TITLE
Blast furnace Specific Inputs

### ISSUE THREAD

**Issue by UrsaMiner** [Quantumshark/TestMod#5]
The Blast Furnace Has 3 Different Item inputs, 1 for each Item.
The Inputs Should ONLY Be Accepted At The Right Input
Top = Input
Sides = Extra
Back = Reducer
Bottom = Output

**Comment by Quantumshark** [comment]
The blast furnace also needs to intake heat.
In real life, all three of the blast furnace's item inputs would be input through the top, with hot air entering from the sides, slag leaving through the sides, and molten iron/steel leaving from the bottom.
Perhaps heat could be input at the sides, with all three inputs at the top and the two different outputs on the back and bottom?
All the current sprites could remain unchanged except the side, on which the input chute currently present could be replaced with a copper section for heat exchange.

**Comment by digit1729** [comment]
I suggest then that we don't make the sides of the blast furnace specific. Items are already sorted only into input slots for which there are recipes that use that item, and hopefully if we ever come up with a situation where the same ingredient can be used in multiple slots, we'll also have conduit interfaces that allow you to target a specific slot.

**Comment by digit1729** [comment]
My thinking now is that rather than hard-coding the sides for machines, we default to any input / output connecting all sides but later introduce configuration so that the player can control which slots can be accessed from which sides - see #21 
This could just be part of the machines, or it could require some kind of automation update to be added to the machine; if the latter, then we could even have different levels of automation upgrade with additional levels of functionality. It could even be that without a basic automation then none of the slots are visible (i.e., even hopper integration is turned off by default).

Closing this issue.
